### ISSUE TITLE
"Submit Results" results in error

### ISSUE THREAD

**Issue by norvins2** [fido-alliance/conformance-tool-issues#1]
The FIDO Conformance test 0.9.4 (UAF 1.0) "Submit Results" dialog "Submit" button results in an error. 

### The contents filled into the dialog are:
_Intel® Online Connect Fingerprint Authenticator (SGX)
Intel Corporation
email address_

Inspector Console Log attached
[SubmitConsole.log](https://github.com/fido-alliance/conformance-tool-issues/files/1399353/SubmitConsole.log)

**Comment by katiew7** [comment]
@norvins2  Please try using the most recent build 0.9.5.  There was a bug fix for this issue.

**Comment by herrjemand** [comment]
Hey @norvins2. Your results actually were successfully submitted. v0.9.4 has a bug that causes to show error message on succes. This issue was resolved in v0.9.5
