### ISSUE TITLE
UAF 1.1 Protocol-Dereg-Req-6 P-1

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#101]
Our client is sending back an UNKNOWN error, because the key ID sent does not match an existing registration. The conformance tool says this is not expected.

In the specification, here is the relevant processing rule:

Create appropriate ASMRequest for Deregister function and send it to the ASM. If the ASM returns an error, handle that error appropriately. The status code returned by the ASM [UAFASM] must be mapped to a status code defined in [UAFAppAPIAndTransport] as specified in section 3.4.6.2.1 Mapping ASM Status Codes to ErrorCode.

Since an non-matching key ID is an error, then the client should return an error.

**Comment by herrjemand** [comment]
@mlourie If client and authenticator receives a deregistration request with unknown keyID it must always succeed of both ASM and Client side. 

Consider this scenario: An attacker wants to find if keyID exists. Attacker can send dereg request with some keyID, and wait for the response. If response successful, then keyID did exist. If dereg failed, then keyID did not exist.

So ASM and Client must always return success for both existing and non-existing keyID
