### ISSUE TITLE
UAF 1.1 Protocol-Dereg-Req-6 P-1

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#107]
This is a follow up to #101.

There are two limits for the size of key id. The FIDO UAF Protocol Specification defines KeyID as:

base64url(byte[32...2048])

However, the FIDO UAF Authenticator Commands specification, section 6.2 Register Command, 6.2.4 Command Description under NORMATIVE section part says:

"If KeyID is not the key handle itself (e.g. such as in case of a second-factor roaming authenticator) - it must be a unique and unguessable byte array with a maximum length of 32 bytes."

For bound authenticators, the KeyID is not the key handle. Hence, passing a KeyID that is not 32 bytes long should always result in an error.

Now in FIDO UAF Authenticator Commands spec in 6.4 Deregister Command/6.4.4 Command Description Normative section it says:

"Deregister command should not explicitly reveal whether the provided keyID was registered or not."

However, since a length other than 32 bytes is invalid, return an error does not reveal whether it is registered on not. If the keyID is not 32 bytes, then it could not have been registered.

**Comment by herrjemand** [comment]
@mlourie You are correct. New build is on it's way.

**Comment by herrjemand** [comment]
Resolved
