### ISSUE TITLE
UAF 1.1 Protocol-Dereg-Req-4 before hook

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#108]
Tool Version 0.8.40

Same as issue #97  which had been fixed for authentication.
Tool sends reg request with not valid AppID which not contains Trusted facets file and expects Successful result.
Client returns UNTRUSTED_FACET_ID
Request from conformance tool:

`{"uafProtocolMessage":"[{\"header\":{\"upv\":{\"major\":1,\"minor\":1},\"op\":\"Reg\",\"appID\":\"https:\/\/fidoalliance.co.nz\"},\"challenge\":\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\",\"username\":\"hello@test.com\",\"policy\":{\"accepted\":[[{\"aaid\":[\"4e4e#4090\"]}]]}}]"}`

after this failure all Protocol-Dereg-Req-4 tests became invisible

**Comment by herrjemand** [comment]
Fixed typo that resulted with unsigned correct appID. Resolved in v0.8.41

**Comment by herrjemand** [comment]
@k-tono Uploading right now
