### ISSUE TITLE
question on appid

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#11]
F-1 accepted null/missing/empty: For this test case MFAC gets authentication request with empty accepted list and returns NO_MATCH but conformance tool expects PROTOCOL_ERROR. See request content below 

```
[{
      "challenge":"Vmh4X08yM1JfS19DR3FBa1RVeEE3WG1uSXJhaGlrUHJMN0xadUc0Sg",
      "header":{
         	"appID":"",
         	"op":"Auth",
"serverData":"eyJ0ZXN0Y2FzZSI6ICJDbGllbnQtQXV0aC1SZXEtNS1GLTEtMiIsICJ0aW1lc3RhbXAiOiAxNDc5MjA1Nzk3Ljc3ODM5NywgImNoYWxsZW5nZSI6ICJWaHhfTzIzUl9LX0NHcUFrVFV4QTdYbW5JcmFoaWtQckw3TFp1RzRKIn0=",
         	"upv":{
            		"major":1,
            		"minor":0
         	}
      },
      "policy":{
         "accepted":[]
      }
   }]
```
Solution: UAF 1.0 spec contains following statement  “Unless otherwise specified, if a WebIDL dictionary member is a List, it must not be an empty list.” and there is no specification that accepted list could be empty so MFAC should be modified to not accept empty “accepted” policy list and return protocol error instead of NO_MATCH
Auth-Resp-4 F-12 appID is not equal to the appID field of the registration request message

[CLARIFICATION REQUIRED] what is appID as undefined?

**Comment by herrjemand** [comment]
Hey @jenkay 

The tool does not expect protocol error, it expects an error in general. I will add modification so it expects specific error.
