### ISSUE TITLE
UAF Protocol-Dereg-Req-4 "Before hook" for F-2

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#116]
Tool version 0.8.47

Seems like wrong AppIDis set for "before hook", trusted facets list does not contain valid facet key

Before Hook request:
`{"uafProtocolMessage":"[{\"header\":{\"upv\":{\"major\":1,\"minor\":1},\"op\":\"Reg\",\"appID\":\"https:\/\/fidoalliance.co.nz\/execute\/8HRDAXUnst68O9LS8mGJ3jKfJf7ot6oMrZLdfJwb\"},\"challenge\":\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\",\"username\":\"hello@test.com\",\"policy\":{\"accepted\":[[{\"aaid\":[\"4e4e#4092\"]}]]}}]"}`
Facet ids list for given AppID:
`{"trustedFacets":[{"version":{"major":1,"minor":0},"ids":["https://fidoalliance.nz/"]}]}`

Client returns UNTRUSTED_FACET_ID but expected SUCCESS

Assertion Error:

```
Error: the number 7 was thrown, throw an Error :)
    at d (build/polyfills.js:3:3991)
    at i.fail (assets/scripts/vendor/mocha.min.js:1:44947)
    at i.failHook (assets/scripts/vendor/mocha.min.js:1:45278)
    at assets/scripts/vendor/mocha.min.js:1:45622
    at n (assets/scripts/vendor/mocha.min.js:1:40729)
    at assets/scripts/vendor/mocha.min.js:1:40861
    at t.invoke (build/polyfills.js:3:11562)
    at n.run (build/polyfills.js:3:6468)
    at build/polyfills.js:3:3767
    at t.invokeTask (build/polyfills.js:3:12256)
    at n.runTask (build/polyfills.js:3:7153)
    at a (build/polyfills.js:3:2312)	

```

**Comment by herrjemand** [comment]
I can't reproduce issue *(

**Comment by herrjemand** [comment]
@k-tono hm... this is weird...

**Comment by herrjemand** [comment]
@k-tono might found an issue

**Comment by herrjemand** [comment]
Resolved

5 дек. 2017 г. 17:49 пользователь "k-tono" <notifications@github.com>
написал:
