### ISSUE TITLE
U2F 1.1 - Lc bytes (for Extended Length Mode) MSB and LSB are switched

### ISSUE THREAD

**Issue by valentinifx** [fido-alliance/conformance-tool-issues#118]
## What protocol and version of the protocol are you testing?

U2F v1.1

## What is the version of the tool are you using?

0.9.301

## Issue description

Accortding to the U2F Specifications for **U2F Message Framing - Extended Length Encoding**:
_In extended length encoding, the maximum length of request-data is 65 535 bytes. Lc is encoded in the following way:
Let Nc = | <request-data> |. If Nc is 0, Lc is omitted. Otherwise, Lc is encoded as:
0 MSB(Nc) LSB(Nc)
Where MSB(Nc) is the most significant byte of Nc, and LSB(Nc) is the least significant byte of Nc._

In the new Conformance Tool it seems that the MSB was switched with the LSB.
The picture below shows a comparison between the Conformance Tool (USB trace log) vs. the old U2F (USB) Compliance Tool:

![lc_extended_wrong_order_msb_lsb_](https://user-images.githubusercontent.com/30896703/33837041-386cf3e4-de9c-11e7-97af-5a836ce33718.png)

Thanks,
Valentin

**Comment by herrjemand** [comment]
Hey @valentinifx. I think I fixed this issue last week. I will upload new build tonight.
