### ISSUE TITLE
UAF V1.0 F-2 AuthenticationResponse contains a valid signature 

### ISSUE THREAD

**Issue by Teddywonseokyoo** [fido-alliance/conformance-tool-issues#121]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Client / ASM+Authr

## What is the version of the tool are you using?

V0.8.50

## Issue description

When I tried test for AuthenticationResponse contains a valid signature test(F-2),
test tool was not request uafmessage.

Next is conformance tool side log.

The rest of the tests were no problem in Authentication tests part.

12-15 10:09:26.599 31039-31039/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(61390)] "Test started: F-2 AuthenticationResponse contains a valid signature", source: file:///android_asset/www/build/main.js (61390)
12-15 10:09:27.649 31039-31039/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 61390 : Test started: F-2AuthenticationResponse contains a valid signature
12-15 10:09:27.649 31039-31039/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(61390)] "Test started: F-2 AuthenticationResponse contains a valid signature", source: file:///android_asset/www/build/main.js (61390)
12-15 10:09:28.509 31039-31039/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 61390 : Test started: F-2 AuthenticationResponse contains a valid signature                                                                                                     
12-15 10:09:28.509 31039-31039/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(61390)] "Test started: F-2 AuthenticationResponse contains a valid signature", source: file:///android_asset/www/build/main.js (61390)
12-15 10:09:29.029 31039-31039/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 61390 : Test started: F-2 AuthenticationResponse contains a valid signature
12-15 10:09:29.029 31039-31039/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(61390)] "Test started: F-2 AuthenticationResponse contains a valid signature", source: file:///android_asset/www/build/main.js (61390)
12-15 10:09:29.589 31039-31039/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 61402 : Test done: F-2 AuthenticationResponse contains a valid signature
12-15 10:09:29.589 31039-31039/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(61402)] "Test done: F-2 AuthenticationResponse contains a valid signature ", source: file:///android_asset/www/build/main.js (61402)
12-15 10:09:29.859 31039-31039/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 61420 : All done
12-15 10:09:29.869 31039-31039/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(61420)] "All done", source: file:///android_asset/www/build/main.js (61420)

￼

**Comment by herrjemand** [comment]
@Teddywonseokyoo Could I have a copy of your Registration and Authentication Req/Resp pairs?

**Comment by Teddywonseokyoo** [comment]
It was a our client problem.
Thank you.
