### ISSUE TITLE
UAF V1.0 Dereg-Req-1 P-1 The array must not contain two dictionaries of the same protocol version

### ISSUE THREAD

**Issue by Teddywonseokyoo** [fido-alliance/conformance-tool-issues#122]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Client / ASM+Authr

## What is the version of the tool are you using?

V0.8.50

## Issue description

The array must not contain two dictionaries of the same protocol version 
Test request message is error.
request Dereg uafmessage is valid 

{"uafProtocolMessage":"[{\"header\":{\"op\":\"Dereg\",\"upv\":{\"major\":1,\"minor\":0},\"appID\":\"\"},\"authenticators\":[{\"aaid\":\"005D#0001\",\"keyID\":\"-sCL86pP3ADoG6ejauDNyjzJBu086P5BlNl3vi7ajy0\"}]}]"}

assertion keyID
092E2000 
**FAC08BF3 AA4FDC00 E81BA7A3 6AE0CDCA 3CC906ED 3CE8FE41 94D977BE 2EDA8F2D**

keyID : -sCL86pP3ADoG6ejauDNyjzJBu086P5BlNl3vi7ajy0\
**FAC08BF3 AA4FDC00 E81BA7A3 6AE0CDCA 3CC906ED 3CE8FE41 94D977BE 2EDA8F2D**

Next is conformance tool side log.

12-15 13:37:43.569 23430-23430/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 61390 : Test started: P-1 The array must not contain two dictionaries of the same protocol version
12-15 13:37:43.569 23430-23430/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(61390)] "Test started: P-1 The array must not contain two dictionaries of the same protocol version ", source: file:///android_asset/www/build/main.js (61390)
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools W/UAF-v1.0-Conformance: executing...
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: message: {"uafProtocolMessage":"[{\"header\":{\"upv\":{\"major\":1,\"minor\":0},\"op\":\"Reg\",\"appID\":\"\"},\"challenge\":\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\",\"username\":\"hello@test.com\",\"policy\":{\"accepted\":[[{\"aaid\":[\"005D#0001\"]}]]}}]"}
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: channel bindings: {"serverEndPoint":null,"tlsServerCertificate":null,"tlsUnique":null,"cid_pubkey":null}
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: origin: null
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: {"uafProtocolMessage":"[{\"header\":{\"upv\":{\"major\":1,\"minor\":0},\"op\":\"Reg\",\"appID\":\"\"},\"challenge\":\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\",\"username\":\"hello@test.com\",\"policy\":{\"accepted\":[[{\"aaid\":[\"005D#0001\"]}]]}}]"}
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Message: {"uafProtocolMessage":"[{\"header\":{\"upv\":{\"major\":1,\"minor\":0},\"op\":\"Reg\",\"appID\":\"\"},\"challenge\":\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\",\"username\":\"hello@test.com\",\"policy\":{\"accepted\":[[{\"aaid\":[\"005D#0001\"]}]]}}]"}
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: channelBindings: {"serverEndPoint":null,"tlsServerCertificate":null,"tlsUnique":null,"cid_pubkey":null}
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: setting callback
12-15 13:37:43.779 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: starting activity
12-15 13:37:43.799 23430-23430/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: : Line 4522 : [object Object]
12-15 13:37:43.799 23430-23430/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(4522)] "[object Object]", source:  (4522)
12-15 13:37:43.819 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Paused the activity.
12-15 13:37:43.819 23430-23482/org.fidoalliance.mobile.conformancetools W/PluginManager: THREAD WARNING: exec() call to uafv10conformancetest.uafOperation blocked the main thread for 41ms. Plugin should use CordovaInterface.getThreadPool().
12-15 13:37:45.229 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Stopped the activity.
12-15 13:37:45.229 23430-23430/org.fidoalliance.mobile.conformancetools V/ActivityThread: updateVisibility : ActivityRecord{3c68dbe token=android.os.BinderProxy@d9b29e2 {org.fidoalliance.mobile.conformancetools/org.fidoalliance.mobile.conformancetools.MainActivity}} show : false
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Incoming Result. Request code = 61904
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaInterfaceImpl: Sending activity result to plugin
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Got Activity Result
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Request Code: 61904
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Result Code: -1
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Intent Type: UAF_OPERATION_RESULT
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperationResult
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Intent { (has extras) }
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Result Code: -1
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Error Code: 0
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Message: {"uafProtocolMessage":"[{\"assertions\":[{\"assertion\":\"AT4nAwM-sQALLgkAMDA1RCMwMDAxDi4HAAEAAQEAAAEKLiAAbE52DkMTahcX2KORmkVe2f7Kv4GPKrnkvC8I_2-gq0kJLiAA-sCL86pP3ADoG6ejauDNyjzJBu086P5BlNl3vi7ajy0NLggAAAAAADwAAAAMLkEABLQmlxZijhEgmiuFdNX_JJL8WzVtQiMUsGjhJypc4UfWKdXjgPR-KJW4wTNpT3g515aWsfLvrnB9-ENZIGUHMYIHPm4CBi5AABcdWC2MOv7wA0gGzSmHFVvf1X2vplvaSqanuIoyG7kbAD4jvKbxNwGcT2sC6UoB4SK1M1s_xR3Nxp-bcKRwWvgFLiYCMIICIjCCAQqgAwIBAgIEOgCFUDANBgkqhkiG9w0BAQsFADA-MQswCQYDVQQGEwJLUjEQMA4GA1UECgwHT0NUQVRDTzEdMBsGA1UEAwwUT0NUQVRDTyBGSURPIFJvb3QgQ0EwHhcNMTcxMjEyMDEyMzIwWhcNMjIxMjEyMDEyMzIwWjAzMQswCQYDVQQGEwJLUjEQMA4GA1UECgwHT0NUQVRDTzESMBAGA1UEAwwJMDA1RCMwMDAxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEYC7o60Pt1to5rRjVfN7okUDzp4GC51kbSPDUC9JTkVPJeIwq3dtbco_UgBEa0YBnaF7-1L9uXkoEjlzljxDeNjANBgkqhkiG9w0BAQsFAAOCAQEAVlBrscFKGcH7wIOhwx9HL_DEwVLNWtY68IV3AqEM_HCmkMWOfJFHy0dA_H53JTSW1l0Vl_Eb-mzlpe8HLntmRYkm6ALJ5Y1abEovKBjqrXrpZUPduDbf4KNUEf9AtRUYcH9tygJzpVthaISEI1Om3afCGRhepiEuxgkNY3e2u39zZO469qd9QXnTIosynPT3UB5k5BGsEfDmTnIwYmul56VDH6otz7Jrs4iqmKQoK_g4iCEGmNulPdHzqRaLHFzvABJD3IaY9HCq4B3p6nHOM6YuXtx69l9OHmIw641oScpbJvMiY4BMG7BiGLbhFjhMZwCG97BRwOLvSvzqJV0bEA\",\"assertionScheme\":\"UAFV1TLV\"}],\"fcParams\":\"eyJhcHBJRCI6ImFuZHJvaWQ6YXBrLWtleS1oYXNoOlQ0bGxhZkFIeFlSa3FYblRqMVJ3NXhtT1NlVSIsImNoYWxsZW5nZSI6Ikg5aVc5eUE5YUFYRl9sZWxRb2lfRGhVazUxNEFkOFRxdjB6Q25DcUtEcG8iLCJjaGFubmVsQmluZGluZyI6e30sImZhY2V0SUQiOiJhbmRyb2lkOmFway1rZXktaGFzaDpUNGxsYWZBSHhZUmtxWG5UajFSdzV4bU9TZVUifQ\",\"header\":{\"appID\":\"\",\"op\":\"Reg\",\"upv\":{\"major\":1,\"minor\":0}}}]"}
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Started the activity.
12-15 13:37:45.289 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Resumed the activity.
12-15 13:37:45.329 23430-23430/org.fidoalliance.mobile.conformancetools I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@d9b29e2 time:199970565
12-15 13:37:45.499 23430-23430/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: : Line 4522 : [object Object]
12-15 13:37:45.499 23430-23430/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(4522)] "[object Object]", source:  (4522)
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools W/UAF-v1.0-Conformance: executing...
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: message: **{"uafProtocolMessage":"[{\"header\":{\"op\":\"Dereg\",\"upv\":{\"major\":1,\"minor\":0},\"appID\":\"\"},\"authenticators\":[{\"aaid\":\"005D#0001\",\"keyID\":\"-sCL86pP3ADoG6ejauDNyjzJBu086P5BlNl3vi7ajy0\"}]}]"}**
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: channel bindings: {"serverEndPoint":null,"tlsServerCertificate":null,"tlsUnique":null,"cid_pubkey":null}
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: origin: null
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperation: {"uafProtocolMessage":"[{\"header\":{\"op\":\"Dereg\",\"upv\":{\"major\":1,\"minor\":0},\"appID\":\"\"},\"authenticators\":[{\"aaid\":\"005D#0001\",\"keyID\":\"-sCL86pP3ADoG6ejauDNyjzJBu086P5BlNl3vi7ajy0\"}]}]"}
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Message: {"uafProtocolMessage":"[{\"header\":{\"op\":\"Dereg\",\"upv\":{\"major\":1,\"minor\":0},\"appID\":\"\"},\"authenticators\":[{\"aaid\":\"005D#0001\",\"keyID\":\"-sCL86pP3ADoG6ejauDNyjzJBu086P5BlNl3vi7ajy0\"}]}]"}
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: channelBindings: {"serverEndPoint":null,"tlsServerCertificate":null,"tlsUnique":null,"cid_pubkey":null}
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: setting callback
12-15 13:37:45.499 23430-23482/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: starting activity
12-15 13:37:45.529 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Paused the activity.
12-15 13:37:45.529 23430-23482/org.fidoalliance.mobile.conformancetools W/PluginManager: THREAD WARNING: exec() call to uafv10conformancetest.uafOperation blocked the main thread for 33ms. Plugin should use CordovaInterface.getThreadPool().
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Incoming Result. Request code = 61904
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaInterfaceImpl: Sending activity result to plugin
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Got Activity Result
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Request Code: 61904
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Result Code: -1
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Intent Type: UAF_OPERATION_RESULT
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: uafOperationResult
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Intent { (has extras) }
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Result Code: -1
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Error Code: 0
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/UAF-v1.0-Conformance: Message: null
12-15 13:37:46.359 23430-23430/org.fidoalliance.mobile.conformancetools D/CordovaActivity: Resumed the activity.
12-15 13:37:46.399 23430-23430/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 312 : Error in Success callbackId: uafv10conformancetest449612883 : SyntaxError: Unexpected end of JSON input
12-15 13:37:46.399 23430-23430/org.fidoalliance.mobile.conformancetools I/chromium: [INFO:CONSOLE(312)] "Error in Success callbackId: uafv10conformancetest449612883 : SyntaxError: Unexpected end of JSON input", source: file:///android_asset/www/cordova.js (312)
12-15 13:37:46.399 23430-23430/org.fidoalliance.mobile.conformancetools D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 61402 : Test done: P-1

**Comment by herrjemand** [comment]
@Teddywonseokyoo On deregistration response success, you need to return an empty UAFProtocolMessage "{}"
