### ISSUE TITLE
U2F 1.1 Authr NFC - Signature counter not in sync

### ISSUE THREAD

**Issue by serianox** [fido-alliance/conformance-tool-issues#123]
## What protocol and version of the protocol are you testing?

U2F v1.1

## What is your implementation class?

NFC authenticator

## What is the version of the tool are you using?

commit 8244a7b

## Issue description

at line 245 in u2f_nfc_test.cc,

```c++
  std::cout << "\nValid U2F_REGISTER, Extended APDU";
  PASS(test_Enroll(EXTENDED_APDU, 0x9000u));
  std::cout << "Check the Signature\n";
  PASS(enrollCheckSignature(regReq, regRsp));

  std::cout << "\nValid U2F_AUTH, Extended APDU";
  PASS(rapduLen = test_Sign(EXTENDED_APDU, 0x9000u));
  std::cout << "Check the Signature & Counter ";
  PASS(signCheckSignature(regReq, regRsp, authReq, authRsp, rapduLen));
  CHECK_EQ(MAKE_UINT32(authRsp.ctr), ctr+1); ctr = MAKE_UINT32(authRsp.ctr);
```

A new key is generated, then the key is used and the counter value returned is checked. The test assume that the counter value returned is the one from the previous authentication plus one. The test incorrectly assume that the counter is common to the newly generated key and the previous key. However, § 2.6 of _U2F Implementation Considerations_ clearly states that

> This counter may be 'global' (i.e., the same counter is incremented regardless of the application parameter in Authentication Request message), or per-application (i.e., one counter for each value of application parameter in the Authentication Request message). 

`CHECK_EQ(MAKE_UINT32(authRsp.ctr), ctr+1);` at line 254 should be removed.

**Comment by serianox** [comment]
`CHECK_EQ(MAKE_UINT32(authRsp.ctr), ctr+1);` at line 265 should also be removed.

**Comment by serianox** [comment]
@herrjemand Sorry for being pushy. Have you had time to review this issue? :(

**Comment by serianox** [comment]
@herrjemand commit [629568f](https://github.com/serianox/u2f-ref-code/commit/629568f50419d5d82f50c873ff6986662c501134)

**Comment by herrjemand** [comment]
@serianox Let me have a look...

**Comment by herrjemand** [comment]
@serianox https://github.com/fido-alliance/google-u2f-ref-code/pull/10

if you build the tool with your change it would be fine. Sorry for the delay.
