### ISSUE TITLE
UAF 1.0 (iOS) Req-Resp not working with the iOS Conformance app

### ISSUE THREAD

**Issue by Leejigun** [fido-alliance/conformance-tool-issues#124]
## What protocol and version of the protocol are you testing?
UAF v1.0

## What is your implementation class?
Authenticator + Client Combo app in iOS.

## What is the version of the tool are you using?
v0.8.48

## Issue description

We are developing an Authenticator + Client Combo app in iOS, and we are currently working on a self-validation.
(This Conformance app received a. ipa file from Yuriy Ackermann.)

At the end of the reg test, the result screen shows that all the parts of Req - Resp have failed, although the url was not received from the Conformance app.

Auth test is also Auth-Resp part fails.

What we want to ask is this.

1) Although client app did not receive url, Why does the Req-Resp and Auth-Resp test (in Auth,Req test) appear as failed on the Results screen?

2)If client app on ios do not require a Resp test, how can we complete self-validation?

We look forward to hearing from you.

**Comment by herrjemand** [comment]
Resolved
