### ISSUE TITLE
FC-API-Android-1 Test P-5 and F-1

### ISSUE THREAD

**Issue by ockyaditia** [fido-alliance/conformance-tool-issues#125]
## What protocol and version of the protocol are you testing?

UAF v1.0 and v1.1

## What is your implementation class?

Client

## What is the version of the tool are you using?

0.8.52

## Issue description

P-5 ->
AssertionError;
CHECK_POLICY returned Fail type errorCode. Expecting Success errorCode of 0x0

uafIntentType request from server UAF_OPERATION, should be CHECK_POLICY

**Comment by herrjemand** [comment]
@ockyaditia Resolved in v0.8.54
