### ISSUE TITLE
Tool does not order mapkeys correctly.

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tool-issues#131]
Map keys in the Relyingparty map are not ordered.

   A2                                   # map(2)
      64                                # text(4)
         6E616D65                       # "name"
      78 18                             # text(24)
         546865204578616D706C6520436F72706F726174696F6E21 # "The Example Corporation!"
      62                                # text(2)
         6964                           # "id"
      73                                # text(19)
         68747470733A2F2F6578616D706C652E636F6D # "https://example.com"

**Comment by herrjemand** [comment]
The alg:

      The keys in every map must be sorted lowest value to highest.
      Sorting is performed on the bytes of the representation of the key
      data items without paying attention to the 3/5 bit splitting for
      major types.  (Note that this rule allows maps that have keys of
      different types, even though that is probably a bad practice that
      could lead to errors in some canonicalization implementations.)
      The sorting rules are:

      *  If two keys have different lengths, the shorter one sorts
         earlier;

      *  If two keys have the same length, the one with the lower value
         in (byte-wise) lexical order sorts earlier.

**Comment by herrjemand** [comment]
@jovasco Should be fixed now. Here is example:

01a401582009a91d7394c7b08a48c644e44184e5f7199bdf7b7020aa5b393529fac29017db02a26269647368747470733a2f2f6578616d706c652e636f6d646e616d657818546865204578616d706c6520436f72706f726174696f6e2103a4626964582030827a2be2e107933610e85eae39dde1b45b673734aafa5c436f58974a3205f76469636f6e782868747470733a2f2f706963732e61636d652e636f6d2f30302f702f61426a6a6a707150622e706e67646e616d65766a6f686e70736d697468406578616d706c652e636f6d6b646973706c61794e616d656d4a6f686e20502e20536d6974680482a263616c672664747970656a7075626c69632d6b6579a263616c6739010064747970656a7075626c69632d6b6579

**Comment by jovasco** [comment]
Looks good for that example.

**Comment by herrjemand** [comment]
@jovasco awesome. Closing then
