### ISSUE TITLE
FC_API_Android-1 F-1 issue

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#132]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
UAFv1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
0.8.58

## Issue description
    In this case we get empty accepted AAID list and return PROTOCOL_ERROR (6), but the tool is expected NO_MATCH(5).
   
    Based on UAF1.1 spec:
    Unless otherwise specified, if a WebIDL dictionary member is a List, it must not be an empty list.

**Comment by herrjemand** [comment]
@jenkay Yes, you are correct. I will update test

**Comment by herrjemand** [comment]
Resolved. New build tonight.

**Comment by herrjemand** [comment]
Ref #141
