### ISSUE TITLE
iOS install of conformance tool fails

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#133]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/U2F v1.0/v1.1/v1.2

## What is your implementation class?
Client

## What is the version of the tool are you using?
0.8.56

## Issue description
FBSApplicationTerminationAssertion; Target BundleID: org.fidoalliance.mobile.conformancetools; Efficacy: Unconditional>
Jan 31 09:51:53 qa--iPhone-X installd(MobileSystemServices)[50] <Notice>: 0x16f457000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundle ID=org.fidoalliance.mobile.conformancetools; Version=0.8.56, ShortVersion=0.8.56>
Jan 31 09:51:53 qa--iPhone-X installd(MobileInstallation)[50] <Notice>: org.fidoalliance.mobile.conformancetools:7:5:1:1:Start : Install (New)
Jan 31 09:51:53 qa--iPhone-X misagent[123] <Notice>: attempt to install invalid profile: 0xe8008012
Jan 31 09:51:53 qa--iPhone-X installd(MobileSystemServices)[50] <Notice>: 0x16f457000 -[MIExecutableBundle installEmbeddedProvisioningProfileWithProgress:]: Could not install embedded profile: 0xe8008012 (This provisioning profile cannot be installed on this device.)
Jan 31 09:51:53 qa--iPhone-X trustd[114] <Notice>: cert[0]: SubjectCommonName =(leaf)[]> 0
Jan 31 09:51:53 qa--iPhone-X trustd[114] <Notice>: cert[0]: CheckLeafMarkerOid =(leaf)[]> 0
Jan 31 09:51:53 qa--iPhone-X trustd[114] <Notice>: cert[0]: IssuerCommonName =(path)[]> 0
Jan 31 09:51:53 qa--iPhone-X installd(Security)[50] <Notice>:  [leaf CheckLeafMarkerOid IssuerCommonName SubjectCommonName]
Jan 31 09:51:53 qa--iPhone-X CommCenter(libBasebandManagerICE.dylib)[84] <Notice>: #I Sending <private> to <private> at 1517421113534
Jan 31 09:51:53 qa--iPhone-X CommCenter(libBasebandManagerICE.dylib)[84] <Notice>: #I Sending <private> to <private> at 1517421113534
Jan 31 09:51:53 qa--iPhone-X CommCenter(libBasebandManagerICE.dylib)[84] <Notice>: #I Sending <private> to <private> at 1517421113535
Jan 31 09:51:53 qa--iPhone-X installd(MobileSystemServices)[50] <Notice>: 0x16f457000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 147: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.96DKAb/extracted/Payload/fido-conformance-tools-ionic.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)
Jan 31 09:51:53 qa--iPhone-X installd(MobileSystemServices)[50] <Notice>: 0x16f457000 -[MIInstaller performInstallationWithError:]: Verification stage failed
Jan 31 09:51:53 qa--iPhone-X assertiond[70] <Notice>: Client relinquished <BKTerminationAssertion: 0x13bd13ca0; "FBSApplicationTerminationAssertion" (Unconditional); 50:(null) id:\M-b\M^@\M-&3D61D3E47E88>
Jan 31 09:51:53 qa--iPhone-X assertiond[70] <Notice>: -[BKAssertion dealloc] - <0x13bd13ca0>
Jan 31 09:51:53 qa--iPhone-X installd(MobileInstallation)[50] <Notice>: org.fidoalliance.mobile.conformancetools:7:5:2:0:Fail (End) : Install (New)
Jan 31 09:51:53 qa--iPhone-X lsd(MobileInstallation)[90] <Notice>: (null):5:1:2:0:MobileInstallation returned nil for file:///var/mobile/Media/PublicStaging/fido-conformance-tools-ionic-v0.8.56.ipa/
Jan 31 09:51:53 qa--iPhone-X mobile_installation_proxy(MobileInstallation)[255] <Notice>: (null):5:1:2:0:_LSInstallationManager install:withError finished
Jan 31 09:51:53 qa--iPhone-X mobile_installation_proxy(MobileSystemServices)[255] <Notice>: 0x16f0a3000 handle_install: Installation failed: Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.96DKAb/extracted/Payload/fido-conformance-tools-ionic.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)" UserInfo={LibMISErrorNumber=-402620395, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=147, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.96DKAb/extracted/Payload/fido-conformance-tools-ionic.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)}
Jan 31 09:51:53 qa--iPhone-X mobile_installation_proxy(MobileCoreServices)[255] <Notice>: Connection invalidated to installationCallbackInterface

**Comment by herrjemand** [comment]
Currently we are distributing iOS tool with ad-hoc model. We are working to upload it to the appstore. In the meanwhile could you please email conformance-tools@fidoalliance.org

Regards
Yuriy
