### ISSUE TITLE
Ad-hoc ios build will not install

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#137]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAFv1.1

## What is your implementation class?

Client

## What is the version of the tool are you using?

fido-conformance-tools-ionic.ipa

## Issue description
After attempting to install the ipa via xcode, an error occurs 'app installation failed.' Screenshot is attached.
![screen shot 2018-02-13 at 9 50 48 am](https://user-images.githubusercontent.com/5342760/36166845-a5e5ddda-10a8-11e8-8993-ff847faf2e98.png)

**Comment by herrjemand** [comment]
Replied in private
