### ISSUE TITLE
"PublicKeyCredentialParameters" has no "id" field in CTAP2 test's Authr-MakeCred-Req-4.js

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-tool-issues#138]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

CTAP2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

v0.9.404-beta

## Issue description

F-5, F-6 and F-7 test items of Authr-MakeCred-Req-4.js
This should be "alg" field instead.

**Comment by herrjemand** [comment]
@nuno0529 thanks for that. Resovled
