### ISSUE TITLE
Authr-MakeCred-Req-4.js 's line-195, wrong expected error code.

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-tool-issues#139]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

CTAP2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
v0.9.404-beta

## Issue description
CTAP2_ERR_UNSUPPORTED_OPTION
should be changed to 
CTAP2_ERR_UNSUPPORTED_ALGORITHM

**Comment by herrjemand** [comment]
Resolved. Thanks @nuno0529 !
