### ISSUE TITLE
UAF 1.1 tests fail with PROTOCOL_ERROR

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#14]
Not able to run any tests for operations, as uafv10conformancetest.js is referenced.

Android client: v0.8.15

chose metadata with 1.1 and loaded test for UAF 1.1
![screen shot 2017-11-01 at 3 03 47 pm](https://user-images.githubusercontent.com/5342760/32300343-4c34df54-bf16-11e7-9deb-041fe5f9cf80.png)

**Comment by jenkay** [comment]
@herrjemand I've retested with v0.8.19 and issue is still reproducible.

**Comment by apowers313** [comment]
@jenkay @vens1 have you tested with .22 or later?

**Comment by jenkay** [comment]
@apowers313 I think we have found the root of the problems, and seems to be on our side. I'll close this issue.
