### ISSUE TITLE
Authr-MakeCred-Req-1.js, wrong pubKeyCredParams test items F-11 & F-12

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-tool-issues#140]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

CTAP2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
v0.9.404-beta

## Issue description
makeCredStruct.user = xxxx should not be existed in test items F-11 & F-12 for pubKeyCredParams

**Comment by herrjemand** [comment]
Thanks @nuno0529! Resolved. New build tonight
