### ISSUE TITLE
FC_API_Android-1 F-1 issue

### ISSUE THREAD

**Issue by ArshakBabasyan** [fido-alliance/conformance-tool-issues#141]
UAF v1.1
Client tests
Tool Version 0.9.1

## Issue description
Client gets request:
{"header":{"upv":{"major":1,"minor":1},"op":"Auth","appID":"","serverData":"5s7n8-7_LDAtRIKKYqbAtTTOezVKCjl2mPorYzbpxRrZ-_3wWroMXsF_pLYjNVm_l7bplAx4bkEwK6ibil9EHGfdfKOQ1q0tyEkNJFOgqdjVmLioroxgThlj8Istpt7q"},"challenge":"HQ1VkTUQC1NJDOo6OOWdxewrb9i5WthjfKIehFxpeuU","policy":{"accepted":[[{"aaid":"947D#F749"}]]}}

Expected result NO_MATCH
Client returns PROTOCOL_ERROR and it is correct response for this request as there the aaid field is string instead of array:
"aaid":"947D#F749"

Based on fido-uaf-protocol-v1.1 the aaid field in MatchCriteria is array not string.

**Comment by herrjemand** [comment]
Yes, you are correct @ArshakBabasyan. Fixed in v0.9.2

Regards. Yuriy
