### ISSUE TITLE
FC_API_Android-1 P-4 issue

### ISSUE THREAD

**Issue by ArshakBabasyan** [fido-alliance/conformance-tool-issues#142]
UAF v1.1
Client tests
Tool Version 0.9.1

## Issue description
Wrong Assertion error.

Assertion error: 
TypeError: Cannot read property 'aaid' of undefined

Client return this discovery data:
{"availableAuthenticators":[{"aaid":"4e4e#4090","assertionScheme":"UAFV1TLV","attachmentHint":1,"attestationTypes":[15880],"authenticationAlgorithm":1,"description":"Silent Authenticator for Android","icon":"data:image/png;base64,iVB..II\u003d","isSecondFactorOnly":false,"keyProtection":6,"matcherProtection":1,"supportedExtensionIDs":[],"supportedUAFVersions":[{"major":1,"minor":0},{"major":1,"minor":1}],"tcDisplay":1,"tcDisplayContentType":"text/plain","title":"Silent ASM","userVerification":512}],"clientVendor":"Nok Nok Labs, Inc","clientVersion":{"major":5,"minor":0},"supportedUAFVersions":[{"major":1,"minor":1},{"major":1,"minor":0}]}

**Comment by herrjemand** [comment]
Thanks for that @ArshakBabasyan 

Resolved in version 0.9.2 (Upload tonight)

Regards. Yuriy
