### ISSUE TITLE
Android API test: FC-API-Android-1 P-4 Issue

### ISSUE THREAD

**Issue by ockyaditia** [fido-alliance/conformance-tool-issues#146]
UAF v1.1
Client-Authr Combo Part
Conformance Tool v0.9.2

### Issue description
Android API test: FC-API-Android-1 P-4

AssertionError: AuthenticatorInfo missing supportedUAFVersion field!: expected undefined to not equal undefined
I see the log for comparison is wrong because it compare with protocol UAF 1.0 {'major':1, 'minor':0}. It must be compare with protocol UAF 1.1 {'major':1, 'minor':1}

**Comment by herrjemand** [comment]
Thanks for reporting. Resolved in 0.9.3
