### ISSUE TITLE
Error : the number was thrown, throw an Error

### ISSUE THREAD

**Issue by ervanux** [fido-alliance/conformance-tool-issues#147]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Client

## What is the version of the tool are you using?

v0.9.2

## Issue description

What does this mean? I have a few case like this. Should I return a different error? 

![img_17e412abf214-1](https://user-images.githubusercontent.com/545894/37196108-9061f0e8-2386-11e8-8a45-d62025894b8f.jpeg)

**Comment by herrjemand** [comment]
@ervanux Looks like you are having issues with you transport api. Please check device logs
