### ISSUE TITLE
Android API tests: FASM-API-Android-1 P-2

### ISSUE THREAD

**Issue by ockyaditia** [fido-alliance/conformance-tool-issues#148]
UAF v1.1
Client Part
Conformance Tool v0.9.2

### Issue description
Android API test: FASM-API-Android-1 P-2

TypeError: Cannot read property 'tcDisplayContentType' of undefined

**Comment by herrjemand** [comment]
@ockyaditia Thanks for reporting. The release 0.9.3 will fix you issue *)
