### ISSUE TITLE
Android API Tests FASM-API - P2

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#15]
This sends valid get info request to asm and gets a valid response back with status OK. It is unclear what is validated but conformance tool shows error  INVALID_TRANSACTION_CONTENT should be <=0 asm response shown below:
 ```
{"responseData":{"Authenticators":[{"aaid":"4e4e#4015","asmVersions":[{"major":1,"minor":0},{"major":1,"minor":1}],"assertionScheme":"UAFV1TLV","attachmentHint":1,"attestationTypes":[15880],"authenticationAlgorithm":1,"authenticatorIndex":0,"description":"PIN Authenticator for Android","hasSettings":true,"icon":"data:image/png;base64,iVBQmCC","isRoamingAuthenticator":false,"isSecondFactorOnly":false,"isUserEnrolled":true,"keyProtection":1,"matcherProtection":1,"supportedExtensionIDs":[],"tcDisplay":1,"tcDisplayContentType":"text/plain","title":"PIN","userVerification":5}]},"statusCode":0} 
```
Icon value is cutted to make response shorter. It is unclear which field is invalid in this successful ASM response.

**Comment by jenkay** [comment]
@herrjemand 
This is still an issue with latest build: v0.8.19

**Comment by herrjemand** [comment]
@jenkay have you tested 0.8.23?

**Comment by apowers313** [comment]
CC @vens1

**Comment by jenkay** [comment]
@apowers313 this may be an issue on our side. I'll close this issue.
