### ISSUE TITLE
Invalid signature issue

### ISSUE THREAD

**Issue by armenabgaryan** [fido-alliance/conformance-tool-issues#150]
UAF v1.1
Client tests
Tool Version 0.9.3

## Issue description
AssertionError:
The signature is invalid!: expected false to be true

Failing test cases:
- Protocol-Reg-Resp-3 P-4
- Protocol-Auth-Resp-3 P-3
- Protocol-Auth-Resp-3 P-4

Mentioned above test cases started to fail with the "The signature is invalid!" Assertion Error after addition of the TAG_EXTENSION (0x3E12) object (with TAG_EXTENSION_ID and TAG_EXTENSION_DATA) to the Reg/Auth assertion.

**Comment by herrjemand** [comment]
@armenabgaryan Are you adding those tags before signing, or after signing?

**Comment by armenabgaryan** [comment]
@herrjemand Before signing.

**Comment by herrjemand** [comment]
@armenabgaryan  Can you email me the copy of your attestations?

**Comment by herrjemand** [comment]
Resolved in v0.9.5
