### ISSUE TITLE
Android API Tests FASM-API - P3

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#16]
This should send valid registration request, but it contains multiple issues, request shown below:
```
{"args":{"appID":"android:apk-key-hash:LK84ci82ruA6u8SyF26cghsVwZg=","attestationType":15879,"finalChallenge":"eyJhcHBJRCI6ImFuZHJvaWQ6YXBrLWtleS1oYXNoOkxLODRjaTgycnVBNnU4U3lGMjZjZ2hzVndaZz0iLCJjaGFsbGVuZ2UiOiJLQi1DeVdWbjQ3eWN4clJOdUZyemFnIiwiY2hhbm5lbEJpbmRpbmciOnt9LCJmYWNldElEIjoiYW5kcm9pZDphcGsta2V5LWhhc2g6TEs4NGNpODJydUE2dThTeUYyNmNnaHNWd1pnPSJ9","username":"hoflNVmABocrVagI4Xsj"},"asmVersion":{"major":1,"minor":0},"authenticatorIndex":1,"requestType":"Register"}
```
Issue #1: AuthenticatorIndex set 1 instead of setting it 0. In prior getInfo request test client returns response with AuthenticatorIndex=0 it seems that conformance tool creates register request without taking in account getinfo response.

Issue #2: After replacing Authenticator index with 0 in client side next issue comes up attestationType=15879 instead of our’s 15880 this value also returned in get info response as well as it set in loaded metadata file.

**Comment by herrjemand** [comment]
@jenkay What protocol version are you referring to?

**Comment by herrjemand** [comment]
Could you try the latest version of the tool and let me know if you are still having those issue?

**Comment by jenkay** [comment]
@herrjemand 

Still reproducible on build v0.8.19

**Comment by herrjemand** [comment]
@jenkay v0.8.22 should've resolved this issue.

**Comment by apowers313** [comment]
@vens1 @jenkay any updates?

**Comment by jenkay** [comment]
@apowers313 this may be an issue on our side. I'll close this issue.
