### ISSUE TITLE
requests for server UAF 1.1 are different than UAF 1.0

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#17]
rest.helper.js is configured differently for different versions of protocol:

UAF v1.0 sends get request as 'Get'
UAF v1.1 sends get request as 'get'

UAF v1.0 sends username as 'userName'
UAF v1.1 sends username as 'username'

Due to these differences, the tool returns a 404 error

UAF v1.0 sends uaf response as '/Send/Reg' & '/Send/Auth'
UAF v1.1 sends uaf response as '/respond'

Used Desktop v0.9.13

**Comment by herrjemand** [comment]
UAFv1.1 uses different API description from v1.0
[server-api-documentation.pdf](https://github.com/fido-alliance/conformance-tool-issues/files/1439285/server-api-documentation.pdf)

I've uploaded this document to build server now

**Comment by herrjemand** [comment]
UAFv1.1 uses different API description from v1.0
[uaf1.1-server-api-documentation.pdf](https://github.com/fido-alliance/conformance-tool-issues/files/1439325/uaf1.1-server-api-documentation.pdf)

I've uploaded this document to build server now
