### ISSUE TITLE
Authentication request with username field in Reg-Req-2 F-10

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#18]
We tried the latest conformance tool, and we are still seeing the op.header is set to Auth.

[{"challenge":"LTVDV2k3WXJYeG1HZ2NzYXpwcEl2RmNlR3ZwNl9PSkFzTEZ1WXZVVg","header":{"appID":"","op":"Auth","serverData":"eyJ0ZXN0Y2FzZSI6ICJDbGllbnQtUmVnLVJlcS0yLUYtMTAtMSIsICJ0aW1lc3RhbXAiOiAxNDc5MjA1Nzk3LjgwMjg5NCwgImNoYWxsZW5nZSI6ICItNUNXaTdZclh4bUdnY3NhenBwSXZGY2VHdnA2X09KQXNMRnVZdlVWIn0=","upv":{"major":1,"minor":0}},"policy":{"accepted":[[{"aaid":["4e4e#4010"]}]]},"username":"hello@test.com"}]

**Comment by herrjemand** [comment]
@mlourie Resolved in v0.8.23
