### ISSUE TITLE
UAF 1.1 - Server-Reg-Req-4 P-10 fails while creating UAF response

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#19]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.13

## Issue description
Server-Reg-Req-4 P-10 fails with:
```
---
P-10 Register three different authenticators with the target server, and check that for each registered AAID and KeyID combo, server returns corresponding MatchCriteria in the disallowed array.‣

    * Error: the number 4 was thrown, throw an Error :)
    at i.fail (js/vendor/mocha.min.js:1:44947)
    at js/vendor/mocha.min.js:1:47420
    at n (js/vendor/mocha.min.js:1:40729)
    at js/vendor/mocha.min.js:1:40861
---

```
The tool is unable to process UAF 1.1 reg request {major = 1, minor = 1}, as it fails in verifyProtocolVersion. fido-uaf-v1.1-conformance-module/utils.js contains the following, which seems to be causing the failure.

```
let protocolVersion = {
    'major': 1,
    'minor': 0
}

```

**Comment by herrjemand** [comment]
Hey @vens1. Could you email conformance-tools@fidoalliance.org on that issue as well?

**Comment by vens1** [comment]
The same issues causes Server-Reg-Resp-1 P-1 and F-1 tests to fail.

**Comment by vens1** [comment]
@herrjemand I tried to email the issue to conformance-tools@fidoalliance.org, but it's bouncing back.

**Comment by vens1** [comment]
@herrjemand After fixing the code locally for the above, ran into other issues. 
- In js/authenticator/KeyEnclave.js, for signatureAlgorithms and publicKeyAlgorithms - the prefix UAF_ need to be removed. 
- After fixing the above this ran into:
==
Error: the string "Cannot read property 'length' of undefined" was thrown, throw an Error :)
    at i.fail (js/vendor/mocha.min.js:1:44947)
    at js/vendor/mocha.min.js:1:47420
    at n (js/vendor/mocha.min.js:1:40729)
    at js/vendor/mocha.min.js:1:40861
==

**Comment by herrjemand** [comment]
Hey @vens1. For some reason conformance-tools@fidoalliance.org is locked for outside emails. I have reported this issue to the I.T. Meanwhile could you email me your server url? yuriy@fidoalliance.org

**Comment by herrjemand** [comment]
I am looking into your issues right now

**Comment by herrjemand** [comment]
@mlourie Resolved in the latest build.

P.S. Build should be out in the next hour
