### ISSUE TITLE
Anonymous function found

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#2]
Attempting to run client registration test will fail for Reg-Req-1.js

anonymous function is for: uafv10conformancetest

Please review screenshot attached.
![screen shot 2017-10-19 at 2 55 45 pm](https://user-images.githubusercontent.com/5342760/31796413-40a91fb6-b4de-11e7-8ba5-a484bf94bba9.png)

**Comment by jenkay** [comment]
actually trying out 0.9.5

**Comment by herrjemand** [comment]
@jenkay You need to drop FIDO UAF JS API polyfill into the app

**Comment by jenkay** [comment]
@herrjemand is there documentation on how to do that?

**Comment by jenkay** [comment]
Will close this issue.
