### ISSUE TITLE
UAF 1.1 - Server-Reg-Req-4 P-11 fails while creating UAF response

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#20]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.13

## Issue description
Server-Reg-Req-4 P-11 fails with:

```
P-11 Register second-factor only roaming authenticator the target server, and check that server returns registered KeyID mixed with "aaid" of the authenticator in the "accepted" Two-Dimentional SEQUENCE([]][]) MatchCriteria.‣
TypeError: Cannot read property 'processUAFOperation' of undefined
    at rest.register.get.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5370:37)

```
It looks like this is due to a typo in Server-Reg-Req-4.js:357. Perhaps, the variable `authenticator` should be replaced with `authr` declared on 348?

**Comment by herrjemand** [comment]
Should be resolved in v0.9.16

**Comment by katiew7** [comment]
@vens1 

Please check v0.9.16

**Comment by jenkay** [comment]
I tried this out on v0.9.17
I receive this:  Error: the string "Cannot read property 'length' of undefined" was thrown, throw an Error :)

**Comment by vens1** [comment]
Same here. The full stack using 0.9.17:

```
P-10 Register three different authenticators with the target server, and check that for each registered AAID and KeyID combo, server returns corresponding MatchCriteria in the disallowed array. ‣
Error: the string "Cannot read property 'length' of undefined" was thrown, throw an Error :)
    at i.fail (js/vendor/mocha.min.js:1:44947)
    at js/vendor/mocha.min.js:1:47420
    at n (js/vendor/mocha.min.js:1:40729)
    at js/vendor/mocha.min.js:1:40861
```

**Comment by herrjemand** [comment]
@mlourie Confirmed the issue. Resolved in the latest build.

P.S. Build should be out in the next hour

**Comment by amitdas2** [comment]
Error: Invalid ReturnUAFRequest! The message is {"statusCode":1200,"uafRequest":[{"header":{"upv":{"major":1,"minor":1},"op":"Reg","appID":"https://192.168.0.179:8080/fido"}}]}
    at GetUAFRequest.sendRequest.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:4547:31)

**Comment by amitdas2** [comment]
can you help me?

Error: Invalid ReturnUAFRequest! The message is {"statusCode":1200,"uafRequest":[{"header":{"upv":{"major":1,"minor":1},"op":"Reg","appID":"https://...."}}]}
    at GetUAFRequest.sendRequest.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:4547:31)

**Comment by amitdas2** [comment]
can you help me ?
Error: Invalid ReturnUAFRequest! The message is {"statusCode":1200,"uafRequest":[{"header":{"upv":{"major":1,"minor":1},"op":"Reg","appID":"https://...."}}]}
    at GetUAFRequest.sendRequest.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:4547:31)

**Comment by nehavij** [comment]
I am getting the same error as @vens1.
Node version - 10.21
Tool version - 1.4.12
UAF 1.1
P-10 Register three different authenticators with the target server, and check that for each registered AAID and KeyID combo, server returns corresponding MatchCriteria in the disallowed array.
Kindly let me know how to fix this.
