### ISSUE TITLE
UAF 1.1 - Server-Reg-Req-4 P-4 fails if only aaid is present in MatchCriteria

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#21]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.13

## Issue description
Server-Reg-Req-4 P-4 fails if only aaid is present in MatchCriteria. As per https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-protocol-v1.1-id-20170202.html#dictionary-matchcriteria-members, "AAID MAY be combined with...". So, AAID may be appear without any other fields.

**Comment by herrjemand** [comment]
Thanks for pointing this one out. This should be resolved in v0.9.17

**Comment by katiew7** [comment]
@vens1 

Can you check  v0.9.17?

**Comment by jenkay** [comment]
@katiew7 

I tried this out on v0.9.17 still reproducible.

**Comment by herrjemand** [comment]
@mlourie Confirmed the issue. Resolved in the latest build.

P.S. Build should be out in the next hour
