### ISSUE TITLE
JavaScript Parse issue in UAF 1.1 extensions test

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#22]
We are seeing JS compile issue when running the extension test. We step through using the remote chrome debugging, and we see the following line:

assert.strictEqual(pareseInt(origin.data), Keystore_Origin.KM_TAG_GENERATED, \`origin MUST be set to ${}. Given ${origin.data}\`);

The compiler complains about ${} and says it expects an extension. For this reason, we cannot run the UAF 1.1. extension tests.

**Comment by herrjemand** [comment]
@mlourie Confirmed the issue. Resolved in the latest build.

P.S. Build should be out in the next hour
