### ISSUE TITLE
Protocol-Reg-Req-5 F-1 Incorrect Error Expected

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#23]
The test description says:

> Send a valid RegistrationRequest, with, exts SEQUENCE containing one valid Extension object, with id of "unknown-id", data, and fail_if_unknown to be true, wait for the response, and check that API response returns PROTOCOL_ERROR(0x06) error.

However, PROTOCOL_ERROR is defined as follows:

> A violation of the UAF protocol occurred. The interaction may have timed out; the origin associated with the message may not match the origin of the calling DOM context, or the protocol message may be malformed or tampered with.

None of these conditions apply.

The description of UNKNOWN is:

> An error condition not described by the above-listed codes.

We believe the expected error should be UNKNOWN, because although the extension is not recognized, the message is not invalid.

**Comment by herrjemand** [comment]
@mlourie You are right. Thanks for pointing that out. I will update the specs and the tool

**Comment by herrjemand** [comment]
Resolved in the latest version
