### ISSUE TITLE
Protocol-Dereg-Req-6 P-1

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#25]
The test says:

> Send DeregistrationRequest with "authenticator" SEQUENCE containing "DeregistrationRequest" with "aaid" field set to the unknown AAID, wait for the response, and check that request succeeds.

However, this test is generating an invalid key ID:

```
'keyID': generateRandomString(20)
```

It should expect PROTOCOL_ERROR, since keyID needs to be base64 encoded.

**Comment by herrjemand** [comment]
@mlourie generateRandomString crypto.getRandomValues that generates secure random buffer, that is then converted to string using base64url encoding. So no, it would not return PROTOCOL_ERROR

However, thank you for bringing up this test, as it contains mistake. If the "aaid" is set to the uknown AAID, then you would return NO_SUITABLE_AUTHENTICATOR (0x05).

This test need to be moved to the negative tests section, and fixed return error code.

**Comment by herrjemand** [comment]
Updated suit in the latest build
