### ISSUE TITLE
UAF 1.1 - Server-Reg-Req-4 P-11 incorrectly looking for registered [AAID,keyID] in Policy.accepted instead of Policy.disallowed

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#26]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
Server-Reg-Req-4 P-11 incorrectly looking for registered [AAID,keyID] in Policy.accepted instead of Policy.disallowed. In registration request, server will need to include registered [AAID,keyID] pairs in Policy.disallowed

**Comment by herrjemand** [comment]
@vens1 P-11 intended to check that server correctly handle second-factor only authenticators, and provides keyID for them in the accepted.

> Register second-factor only roaming authenticator the target server, and check that server returns registered KeyID mixed with "aaid" of the authenticator in the "accepted" Two-Dimentional SEQUENCE([]][]) MatchCriteria.

So the test is performing as expected

**Comment by vens1** [comment]
That's applicable to authentication request generation by the server. However, for registration request generation, 3.4.6.1.1.2 (https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-protocol-v1.1-id-20170202.html#registration-request-generation-rules-for-fido-server) applies, i.e.:

`The FIDO Server must include already registered AAIDs and KeyIDs into field p.disallowed to hint that the client should not register these again.`

**Comment by herrjemand** [comment]
@vens1 You are correct. Moved test to the auth tests.
