### ISSUE TITLE
Missing FIDO Conformance Tools instructions for desktop

### ISSUE THREAD

**Issue by eugenInfineon** [fido-alliance/conformance-tool-issues#3]
No instructions how the tool can be used on a PC.

**Comment by herrjemand** [comment]
@eugenInfineon When downloading builds it has instructions in the root folder. Same instructions apply for both Mac and Windows
[FIDO Conformance Tools instructions (1).pdf](https://github.com/fido-alliance/conformance-tool-issues/files/1408562/FIDO.Conformance.Tools.instructions.1.pdf)
