### ISSUE TITLE
UAF 1.1: Deregistration requests are being sent concurrently

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#31]
Deregistration requests are being sent concurrently.The client receives new requests before the old request have completed. On a typical run, this happens 16 times.

**Comment by herrjemand** [comment]
This is weird. The tests are sending requests and are waiting until they are fulfilled.

**Comment by mlourie** [comment]
Our client logs any time concurrent requests are greater than 1:

11-08 15:14:05.955 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:14:05.982 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
11-08 15:14:27.066 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:14:27.090 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
11-08 15:14:30.313 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:14:30.337 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
11-08 15:14:51.411 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:14:51.425 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
11-08 15:14:54.244 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:14:54.274 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
11-08 15:15:15.342 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:15:15.359 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
11-08 15:15:36.748 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:15:36.792 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
11-08 15:15:58.118 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 2
11-08 15:15:58.208 11732-11732/com.noknok.android.mfac.service E/CONF_: concurent request received, active request count : 3
