### ISSUE TITLE
UAF 1.1: Android API Tests requests are being sent concurrently

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#32]
API requests are being sent concurrently.The client receives new requests before the old request have completed. On a typical run, this happens 2 times.

**Comment by herrjemand** [comment]
Ref #31

**Comment by mlourie** [comment]
Our client logs anytime the concurrent requests are greater than 1:

11-08 19:25:14.252 489-489/com.noknok.android.client.asm.service.silent I/CNF: Concurrent request received, active request count : 2
11-08 19:25:14.552 489-489/com.noknok.android.client.asm.service.silent I/CNF: Concurrent request received, active request count : 2

**Comment by herrjemand** [comment]
Ref #67

**Comment by herrjemand** [comment]
@mlourie I am still struggling to figure out where does the concurrency issues coming from, as I am just with no issue run all of the tests.

**Comment by herrjemand** [comment]
@mlourie What phone are you using?

**Comment by mlourie** [comment]
We have test this on multiple devices. Have you run our client and ASM to see if the log entry is produced on your device?

**Comment by herrjemand** [comment]
@mlourie Newest version should resolve this issue
