### ISSUE TITLE
UAF 1.1: FC-API-Android-1

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#37]
P-6 Fail
Assertion: Error: [object ErrorEvent]
(undefined:undefined)

P-7 Fail
Assertion: Error: [object ErrorEvent]
(undefined:undefined)

F-1 Fail
Assertion: Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure “done()” is called; if returning Promise, ensure it resolves

It looks like the conformance tool is missing the FC-API-Adroid-1-F-1-1.test.json data file in the APK.

**Comment by herrjemand** [comment]
Resolved
