### ISSUE TITLE
UAF 1.1 - Server-Reg-Resp-5 - F-1 through  F-8 tests fail in the tool with "TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#39]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
Test cases F-1 through F-8 fail with the same error in the tool.
```
F-2 Get registration request, and generate registration response with "assertions[].assertion" is NOT base64url encoded, and send it to the server. Server must reject response. ‣
TypeError: Cannot read property '0' of undefined
    at rest.register.get.then.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:6350:36)
```

**Comment by herrjemand** [comment]
Resolved
