### ISSUE TITLE
UAF 1.1 - Server-Auth-Resp-1 P-1 Sends auth response with empty assertion

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#46]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
The test tool is sending an authentication response with empty assertion to the Server. Here is the response received by the server, which it rejects as expected.

`[{"header":{"upv":{"major":1,"minor":1},"op":"Auth","appID":"https://server-test.noknoktest.com:8443/tutorial/uaf/facets.uaf","serverData":"_XdRp8glddIG5Vin5IfbS91vW6QRnD_0E7bxKV1ycGYb2tuAsQos1sxFrwAO9TnWbWlcYeEu4iq_cif6oeLqlxGVq10qVD0VsK2BiAi4L6U10hgvZkpFkqYmhTR83ocGNm_At-WWCVu0_5Bs55_8K8aR8RtkLEYL"},"fcParams":"eyJmYWNldElEIjoiaHR0cHM6Ly90ZXN0LWFkYXB0ZXIubm9rbm9rdGVzdC5jb20vTUdUL3dlYmFwaS90b29sL25hdGl2ZSIsImFwcElEIjoiaHR0cHM6Ly9zZXJ2ZXItdGVzdC5ub2tub2t0ZXN0LmNvbTo4NDQzL3R1dG9yaWFsL3VhZi9mYWNldHMudWFmIiwiY2hhbGxlbmdlIjoibk92U1I2UnRCT0dDQkxsNGVxdWRfZDNSOHh3SDVuOTNXX01QeWRUUzBYayIsImNoYW5uZWxCaW5kaW5nIjp7fX0","assertions":[{"assertionScheme":"UAFV1TLV","assertion":""}]}]`

**Comment by vens1** [comment]
Also the same issue occurs with Server-Auth-Resp-7 P-1 through P-12.

**Comment by herrjemand** [comment]
@vens1 Should be resolved. Newest version should be up in the next few hours.

**Comment by herrjemand** [comment]
Ref #48

**Comment by herrjemand** [comment]
Resolved
