### ISSUE TITLE
UAF 1.1 - Server-Auth-Resp-6 fails to load due to SyntaxError: Unexpected token ;

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#47]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
Server-Auth-Req-6 fails to load in the tool. It fails with` SyntaxError: Unexpected token ;`

**Comment by herrjemand** [comment]
Resolved
