### ISSUE TITLE
UAF 1.1 - Server-Auth-Resp-7 F-1 through F-12 fail in the tool

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#48]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
F-1 through F-12 fail with the following error in the tool:

```
F-1 Get authenticate request, generate an authenticate response that uses UAF_ALG_SIGN_SECP256R1_ECDSA_SHA256_RAW as signature algorithm, UAF_ALG_KEY_ECC_X962_RAW for public key encoding. Invalidate the signature(by randomly modifying it), and send it to the server. Server must reject response. ‣
TypeError: Cannot read property 'TAG_SIGNATURE' of undefined
    at rest.register.get.then.then.then.then.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5449:91)

```

**Comment by herrjemand** [comment]
@vens1 Should be resolved. Could you check the latest version?
