### ISSUE TITLE
UAF 1.1 - Server-Dereg0-Req-3 P-4 serverData check is incorrect

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#51]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
Deregistration request need not contain serverData, and optional field in OperationHeader. The test incorrectly expects to always find serverData in the request, and fails if it does not find it.

```
P-4 If OperationHeader contains "serverData" field, it must be: (a) of type DOMString (b) it minimum length must be 1 character (c) it maximum length must be 1536 characters ‣
AssertionError: serverData MUST be of type DOMString!: expected undefined to be a string
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5150:16)
    at r (js/vendor/mocha.min.js:1:40757)
    at r.run (js/vendor/mocha.min.js:1:41838)
    at i.runTest (js/vendor/mocha.min.js:1:46569)
    at js/vendor/mocha.min.js:1:47206
    at r (js/vendor/mocha.min.js:1:45957)
    at js/vendor/mocha.min.js:1:46026
    at n (js/vendor/mocha.min.js:1:45394)
    at js/vendor/mocha.min.js:1:45868
    at i (js/vendor/mocha.min.js:1:571)
```

**Comment by herrjemand** [comment]
Resolved
