### ISSUE TITLE
UAF 1.1 - Server-Auth-Req-4 P-8 fails in the tool

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#54]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.19

## Issue description

```
P-8 Register second-factor only roaming authenticator the target server, and check that server returns registered KeyID mixed with "aaid" of the authenticator in the "accepted" Two-Dimentional SEQUENCE([]][]) MatchCriteria. ‣
TypeError: Cannot read property 'parser' of undefined
    at rest.register.get.then.then (eval at compileCode (js/sandbox.js:25:26),

```

**Comment by herrjemand** [comment]
Resolved. Build should be up in an hours or so
