### ISSUE TITLE
UAF 1.1 Authentication test F-54

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#57]
UAF v1.1
Client tests
Tool Version 0.8.28

Client gets request:
`{"uafProtocolMessage":"[{"header":{"upv":{"major":1,"minor":1},"op":"Auth","appID":"","serverData":"5s7n8-7_LDAtRIKKYqbAtTTOezVKCjl2mPorYzbpxRrZ-_3wWroMXsF_pLYjNVm_l7bplAx4bkEwK6ibil9EHGfdfKOQ1q0tyEkNJFOgqdjVmLioroxgThlj8Istpt7q"},"challenge":"HQ1VkTUQC1NJDOo6OOWdxewrb9i5WthjfKIehFxpeuU","policy":{"accepted":[[{"aaid":["FFFF#FFFF"]}],[{"aaid":["4e4e#4091"]}]],"disallowed":[{"aaid":["4e4e#4091"],"exts":[{"id":"unknown-id","data":"","fail_if_unknown":false}]}]}}]"}`

Expected result SUCCESS
Client returns NO_MATCH it is correct response for this request as far as only registered aaid 4e4e#4091 is in disallowed list, also there is unknown extension in match criteria but as far as fail_if_unknown = false so anyway this match criteria in disallowed list is matching the only registered authenticator so NO_MATCH is returned

**Comment by herrjemand** [comment]
Dublicate of #72
