### ISSUE TITLE
UAF 1.1 Authentication test F-54

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#58]
UAF v1.1
Client tests
Tool Version 0.8.28

Client gets request:

`{"uafProtocolMessage":"[{"header":{"upv":{"major":1,"minor":1},"op":"Auth","appID":"","serverData":"5s7n8-7_LDAtRIKKYqbAtTTOezVKCjl2mPorYzbpxRrZ-_3wWroMXsF_pLYjNVm_l7bplAx4bkEwK6ibil9EHGfdfKOQ1q0tyEkNJFOgqdjVmLioroxgThlj8Istpt7q"},"challenge":"HQ1VkTUQC1NJDOo6OOWdxewrb9i5WthjfKIehFxpeuU","policy":{"accepted":[[{"aaid":["FFFF#FFFF"]}],[{"aaid":["4e4e#4091"]}]],"disallowed":[{"aaid":["4e4e#4091"],"exts":[{"id":"unknown-id","data":"","fail_if_unknown":true}]}]}}]"}`

Expected result PROTOCOL_ERROR
Client returns SUCCESS, it is correct response for this request as accepted policy contains {"aaid":["4e4e#4091"]} match criteria which is matching registered authenticator in other hand disallowed match criteria with same aaid contains extension with fail_if_unknown=true so disallowed criteria fails on matching, so client should successfully proceed request with accepted policy.

**Comment by herrjemand** [comment]
Dublicate of #72
