### ISSUE TITLE
Protocol-Auth-Req-5 F-1 Incorrect Error Expected

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#59]
Tool Version 0.8.28
The test description says:

> Send a valid AuthenticationRequest, with, exts SEQUENCE containing one valid Extension object, with id of "unknown-id", data, and fail_if_unknown to be true, wait for the response, and check that API response returns PROTOCOL_ERROR(0x06) error.

However, PROTOCOL_ERROR is defined as follows:

> A violation of the UAF protocol occurred. The interaction may have timed out; the origin associated with the message may not match the origin of the calling DOM context, or the protocol message may be malformed or tampered with.

None of these conditions apply.

The description of UNKNOWN is:

> An error condition not described by the above-listed codes.

We believe the expected error should be UNKNOWN, because although the extension is not recognized, the message is not invalid.

**Comment by herrjemand** [comment]
Resolved in the latest build. New version should be out in few hours
