### ISSUE TITLE
Server: Reg-Resp-4 F-1 Test authenticator does not handle null/empty/missing appID

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#6]
The test authenticator used by the conformance tool does not handle UAF request messages with null/empty/missing AppID. This causes Reg-Resp-4 F-1 to fail during UAF response generation. 
<img width="558" alt="screen shot 2017-10-20 at 12 07 54 pm" src="https://user-images.githubusercontent.com/5342760/31837885-5c2d2ffa-b58f-11e7-9300-f5f5b90093ad.png">

**Comment by herrjemand** [comment]
Resolved in v0.9.7
