### ISSUE TITLE
UAF 1.1 Registration Test F-27

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#60]
UAF v1.1
Client tests
Tool Version 0.8.28

Client gets request:

`{"uafProtocolMessage":"[{"header":{"upv":{"major":1,"minor":1},"op":"Reg","appID":""},"challenge":"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo","username":"hello@test.com","policy":{"accepted":[[{"aaid":["4e4e#4091"]}],[{"aaid":["4e4e#4091"],"exts":[{"id":"unknown-id","data":"","fail_if_unknown":true}]}]]}}]"}`

Expected result PROTOCOL_ERROR
Client returns SUCCESS as far as there is accepted separate criteria {"aaid":["4e4e#4091"]} registered authenticator matches this criteria, there is also criteria with extension with fail_if_unknown=true and client fails on matching this criteria but it still could successfully authenticate with first criteria.

**Comment by herrjemand** [comment]
Dublicate of #72
