### ISSUE TITLE
UAF 1.1 Registration test F-54

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#61]
UAF v1.1
Client tests
Tool Version 0.8.28

Client gets request:

`{"uafProtocolMessage":"[{"header":{"upv":{"major":1,"minor":1},"op":"Reg","appID":""},"challenge":"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo","username":"hello@test.com","policy":{"accepted":[[{"aaid":["4e4e#4091"]}]],"disallowed":[{"aaid":["4e4e#4091"],"exts":[{"id":"unknown-id","data":"","fail_if_unknown":true}]}]}}]"}`

Expected result PROTOCOL_ERROR
Client returns SUCCESS, it is correct response for this request as accepted policy contains {"aaid":["4e4e#4091"]} match criteria which is matching registered authenticator in other hand disallowed match criteria with same aaid contains extension with fail_if_unknown=true so disallowed criteria fails on matching, so client should successfully proceed request with accepted policy.

**Comment by herrjemand** [comment]
Dublicate of #72
