### ISSUE TITLE
UAF 1.1 Registration test F-54 

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#62]
UAF v1.1
Client tests
Tool Version 0.8.28

Client gets request:

`{"uafProtocolMessage":"[{"header":{"upv":{"major":1,"minor":1},"op":"Reg","appID":""},"challenge":"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo","username":"hello@test.com","policy":{"accepted":[[{"aaid":["4e4e#4091"]}]],"disallowed":[{"aaid":["4e4e#4091"],"exts":[{"id":"unknown-id","data":"","fail_if_unknown":false}]}]}}]"}`

Expected result SUCCESS
Client returns NO_MATCH it is correct response for this request as far as only registered aaid 4e4e#4091 is in disallowed list, also there is unknown extension in match criteria but as far as fail_if_unknown = false so anyway this match criteria in disallowed list is matching the only registered authenticator so NO_MATCH is returned

**Comment by herrjemand** [comment]
Dublicate of #72
