### ISSUE TITLE
UAF 1.1  Protocol-Reg-Resp-2 P-1 and P-2

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#71]
Based on fido-uaf-protocol-v1.1 documentation: 

1.OpearationHeader:
If the appID is missing or empty in the request, the FIDO UAF Client must set it to the FacetID of the caller.
https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-protocol-v1.1-id-20170202.html#widl-OperationHeader-appID

2.FinalChallengeParams:
The value must be taken from the appID field of the OperationHeader.
https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-protocol-v1.1-id-20170202.html#widl-FinalChallengeParams-appID

https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-protocol-v1.1-id-20170202.html#registration-request-processing-rules-for-fido-uaf-clients

So, If the appID is missing or empty in the request, client should set both header.appID and fcParams.appID to the FacetID.

**Comment by herrjemand** [comment]
No, the client must only modify fcp. Header is only copied unmodified to the response header.

The FIDO UAF Client must follow the steps:

1. Create an AuthenticationResponse message
2. Copy AuthenticationRequest.header into AuthenticationResponse.header

I know that specs are confusing at this matter.
