### ISSUE TITLE
UAF 1.1: FC-API-Android-1 P-6 and P-7

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#73]
P-6 and P-7 tests do not accept "upv":{"major":1,"minor":1} response for "upv":{"major":1,"minor":1} request. minor must be set to zero.

For example, for P-6 the request is as follows:

[{"header":{**"upv":{"major":1,"minor":1}**,"op":"Reg","appID":""},"challenge":"IR9celOoUv1BuEsThdwNVQv","username":"hello@test.com","policy":{"accepted":[[{"aaid":["FFFF#0001"]}],[{"aaid":["D409#0101"]}],[{"aaid":["D409#0201"]}],[{"aaid":["D409#0501"]}],[{"aaid":["D409#0301"]}],[{"aaid":["D409#0601"]}],[{"aaid":["D409#0701"]}],[{"aaid":["D409#0801"]}],[{"aaid":["4e4e#4090"]}]]}}]

and for the response:

[{"assertions":[{"assertion":"AT79AAM-sQALLgkANGU0ZSM0MDkwDi4HAAABAQEAAAEKLiAANJN12WKy6cSjcPAEl1LckHydkHgPIdEFzrst_qW8h_4JLiAAjyd5XEdn266PY8QoapYC10G_NIFWjDi8tGztZjdD80oNLggANAYAACEEAAAMLkEABPssSQzFlgfp8wUSvtjkB7U45fuZvcDRg9ireY5HYniHzosKNOggOALfUM1bidYfj7Ft0wOVbM1xesa3MFaNvdAIPkQABi5AADZFamIfNv-iva1Ft14KfkvUerJ07kYzbgMphz8peFs1bdWCyg-WJDvFr-xqt_eAyMN-u2SD3lryw4h8RNXWJSg","assertionScheme":"UAFV1TLV"}],"fcParams":"eyJhcHBJRCI6ImFuZHJvaWQ6YXBrLWtleS1oYXNoOlQ0bGxhZkFIeFlSa3FYblRqMVJ3NXhtT1NlVSIsImNoYWxsZW5nZSI6IklSOWNlbE9vVXYxQnVFc1RoZHdOVlF2IiwiY2hhbm5lbEJpbmRpbmciOnt9LCJmYWNldElEIjoiYW5kcm9pZDphcGsta2V5LWhhc2g6VDRsbGFmQUh4WVJrcVhuVGoxUnc1eG1PU2VVIn0","header":{"appID":"","op":"Reg",**"upv":{"major":1,"minor":1}**}}]

the conformance tool fails the test and reports:

Error: [object ErrorEvent]
(undefined:undefined)

If I change the upv minor in the response from 1 to 0, ie **"upv":{"major":1,"minor":0}**, the test passes.

The situation is the same for the P-7 test

**Comment by herrjemand** [comment]
Resolved in v0.8.33 (out in few hours)
