### ISSUE TITLE
UAF 1.0 - Metadata statement for FFFF#FCOD is invalid

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#74]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.21

## Issue description
Metadata statement for FFFF#FC0D is invalid. It contains a non-empty value for attestationRootCertificates while attestationTypes is set to 15580 (TAG_ATTESTATION_BASIC_SURROGATE). This is an invalid combination as per section 4.1 in [FIDO UAF Authenticator Metadata Statements v1.0](https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-authnr-metadata-v1.0-ps-20141208.html)

`In the case of surrogate basic attestation (see [UAFProtocol], section "Surrogate Basic Attestation"), no attestation root certificate is required/used. So this array must be empty in that case.
`

**Comment by herrjemand** [comment]
Resolved.
Thanks for that @vens1!
