### ISSUE TITLE
UAF 1.0 and 1.1 - Intermittent failure - "Error: Timeout of 2000ms exceeded..."

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#75]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0 and 1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.21

## Issue description
Some of the tests fail to complete due to a timeout error such as the one below. This is an intermittent issue and not consistently reproducible.

```
Auth-Req-2 Test the AuthenticationRequest dictionary
"before all" hook ‣
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at js/vendor/mocha.min.js:1:40022

```

**Comment by herrjemand** [comment]
@vens1 looks like for some operations it takes more than 2000ms to be completed. 

I will increase timeout to account for that.
