### ISSUE TITLE
UAF 1.1: P-4/5/6 FASM-API-Android-1

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#78]
The issue with P-2 is resolved for us:

https://github.com/fido-alliance/conformance-tool-issues/issues/30

and as a result P-3 now succeeds. 

But now we are getting "keyID is undefined because P-3is failing: expected undefined to not equal undefined" errors for P-4, P-5, and P-6.

But P-3 did not fail?

**Comment by herrjemand** [comment]
@jenkay Fixed in v0.8.34
