### ISSUE TITLE
UAF 1.1: Extension tests

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#79]
Both extension tests fail for us. We see file not found errors for Protocol-Reg-Resp-P.test.json:

polyfills.js:3 GET file:///android_asset/www/assets/modules/fido-uaf-v1.1-conformance-module/static_json_responses/Protocol-Reg-Resp-P.test.json net::ERR_FILE_NOT_FOUND

I don't see that file in the APK resources?

FC-API-Adroid-1-F-1-1.test.json	FC-API-DOM-1-P-4.test.json
FC-API-Adroid-1-F-1.test.json	FC-API-DOM-1-P-5.test.json
FC-API-Adroid-1-P-4.test.json	FC-API-DOM-1-P-6.test.json
FC-API-Adroid-1-P-5.test.json	FC-API-DOM-1-P-7.test.json
FC-API-Adroid-1-P-6.test.json	Protocol-Auth-Req-P.test.json
FC-API-Adroid-1-P-7.test.json	Protocol-Dereg-Req-P.test.json
FC-API-DOM-1-F-1.test.json	Protocol-Reg-Req-P.test.json

and this result for test P-1:

     Error: the string "can't find PEM header: undefined" was thrown, throw an Error :)

and this result for test P-2:

     Error: the object {

  "_body": "[object ProgressEvent]"

  "headers": {

    "_headers": "[object Map]"

    "_normalizedNames": "[object Map]"

  }

  "ok": false

  "status": 0

  "statusText": ""

  "type": 3

  "url": [null]

} was thrown, throw an Error :)

**Comment by herrjemand** [comment]
@jenkay Should be resolved in v0.8.34. (out in few hours).

**Comment by herrjemand** [comment]
@jenkay One of the issues that you are having is that you are returning certificate chain with new line characters. It's an expected issue, since old version of the UAF Registry had mistake in its example. It was fixed in the UAFv1.2 candidate. Here is what it should look like:

Get attestation chain
```java
Calendar notBefore = Calendar.getInstance();
Calendar notAfter = Calendar.getInstance();
notAfter.add(Calendar.YEAR, 10);

KeyPairGenerator kpGenerator = KeyPairGenerator.getInstance(
  KeyProperties.KEY_ALGORITHM_EC, "AndroidKeyStore");
kpGenerator.initialize(
  new KeyGenParameterSpec.Builder(keyUUID, KeyProperties.PURPOSE_SIGN)
    .setDigests(KeyProperties.DIGEST_SHA256)
    .setAlgorithmParameterSpec(new ECGenParameterSpec("prime256v1"))
    .setCertificateSubject(
      new X500Principal(String.format("CN=%s, OU=%s",
        keyUUID, aContext.getPackageName())))
    .setCertificateSerialNumber(BigInteger.ONE)
    .setKeyValidityStart(notBefore.getTime())
    .setKeyValidityEnd(notAfter.getTime())
    .setUserAuthenticationRequired(true) 
    .setAttestationChallenge(fcHash) -- bind to Final Challenge
    .build());

kpGenerator.generateKeyPair(); // generate Uauth key pair

Certificate[] certarray=myKeyStore.getCertificateChain(keyUUID);
String certArray[]=new String[certarray.length];
int i=0;
for (Certificate cert : certarray) {
    byte[] buf = cert.getEncoded();
    certArray[i] = new String(Base64.encode(buf, Base64.DEFAULT))
            .replace("\n", ""); //Remove any new line characters
    i++;
}

JSONArray jarray=new JSONArray(certArray);
String key_attestation_data=jarray.toString();
```

Response
```
[{"id": "fido.uaf.android.key_attestation", "data": "[\"MIIClDCCAjugAwIBAgIBATAKBggqhkjOPQQD
AjCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFTATBgNVBAoMDEdvb2dsZSwgSW5jLjEQMA4GA1UECwwHQW5k
cm9pZDE7MDkGA1UEAwwyQW5kcm9pZCBLZXlzdG9yZSBTb2Z0d2FyZSBBdHRlc3RhdGlvbiBJbnRlcm1lZGlhdGUwIBcNNzAwMTAx
MDAwMDAwWhgPMjEwNjAyMDcwNjI4MTVaMB8xHTAbBgNVBAMMFEFuZHJvaWQgS2V5c3RvcmUgS2V5MFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEJ/As4L+Kgbcxwcx+5LPQi35quIxg981k/TeWr2IPBLh8+NJ+buDBhQ9O5ln6B7JjbJc4Fvko1Pdz7spKTQdWpKOB
+zCB+DALBgNVHQ8EBAMCB4AwgccGCisGAQQB1nkCAREEgbgwgbUCAQIKAQACAQEKAQEEBkZDSEFTSAQAMGm/hT0IAgYBXtPjz6C/
hUVZBFcwVTEvMC0EKGNvbS5hbmRyb2lkLmtleXN0b3JlLmFuZHJvaWRrZXlzdG9yZWRlbW8CAQExIgQgdM/LUHSI9SkQhZHHpQWR
nzJ3MvvB2ANSauqYAAbS2JgwMqEFMQMCAQKiAwIBA6MEAgIBAKUFMQMCAQSqAwIBAb+DeAMCAQK/hT4DAgEAv4U/AgUAMB8GA1Ud
IwQYMBaAFD/8rNYasTqegSC41SUcxWW7HpGpMAoGCCqGSM49BAMCA0cAMEQCICgYLmk24alwS9Lm06y2lLiqWDddrWh4gmUUv4+A
5k2TAiAEttheSBBaNbQJGQCh3mY92v8nP5obU60IKjpPetRswQ==\",\"MIICeDCCAh6gAwIBAgICEAEwCgYIKoZIzj0EAwIwgZg
xCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MRUwEwYDVQQKDAxHb29nbGU
sIEluYy4xEDAOBgNVBAsMB0FuZHJvaWQxMzAxBgNVBAMMKkFuZHJvaWQgS2V5c3RvcmUgU29mdHdhcmUgQXR0ZXN0YXRpb24gUm9
vdDAeFw0xNjAxMTEwMDQ2MDlaFw0yNjAxMDgwMDQ2MDlaMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEVMBM
GA1UECgwMR29vZ2xlLCBJbmMuMRAwDgYDVQQLDAdBbmRyb2lkMTswOQYDVQQDDDJBbmRyb2lkIEtleXN0b3JlIFNvZnR3YXJlIEF
0dGVzdGF0aW9uIEludGVybWVkaWF0ZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOueefhCY1msyyqRTImGzHCtkGaTgqlzJhP
+rMv4ISdMIXSXSir+pblNf2bU4GUQZjW8U7ego6ZxWD7bPhGuEBSjZjBkMB0GA1UdDgQWBBQ//KzWGrE6noEguNUlHMVlux6RqTA
fBgNVHSMEGDAWgBTIrel3TEXDo88NFhDkeUM6IVowzzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIChDAKBggqhkj
OPQQDAgNIADBFAiBLipt77oK8wDOHri/AiZi03cONqycqRZ9pDMfDktQPjgIhAO7aAV229DLp1IQ7YkyUBO86fMy9Xvsiu+f+uXc
/WT/7\",\"MIICizCCAjKgAwIBAgIJAKIFntEOQ1tXMAoGCCqGSM49BAMCMIGYMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaW
Zvcm5pYTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzEVMBMGA1UECgwMR29vZ2xlLCBJbmMuMRAwDgYDVQQLDAdBbmRyb2lkMTMwMQ
YDVQQDDCpBbmRyb2lkIEtleXN0b3JlIFNvZnR3YXJlIEF0dGVzdGF0aW9uIFJvb3QwHhcNMTYwMTExMDA0MzUwWhcNMzYwMTA2MD
A0MzUwWjCBmDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxFTATBgNVBA
oMDEdvb2dsZSwgSW5jLjEQMA4GA1UECwwHQW5kcm9pZDEzMDEGA1UEAwwqQW5kcm9pZCBLZXlzdG9yZSBTb2Z0d2FyZSBBdHRlc3
RhdGlvbiBSb290MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7l1ex+HA220Dpn7mthvsTWpdamguD/9/SQ59dx9EIm29sa/6Fs
vHrcV30lacqrewLVQBXT5DKyqO107sSHVBpKNjMGEwHQYDVR0OBBYEFMit6XdMRcOjzw0WEOR5QzohWjDPMB8GA1UdIwQYMBaAFM
it6XdMRcOjzw0WEOR5QzohWjDPMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgKEMAoGCCqGSM49BAMCA0cAMEQCIDUho+
+LNEYenNVg8x1YiSBq3KNlQfYNns6KGYxmSGB7AiBNC/NR2TB8fVvaNTQdqEcbY6WFZTytTySn502vQX3xvw==\"]", "fail_if_unknown": false}]
```

**Comment by herrjemand** [comment]
> If the request extension was successfully processed, the <code>data</code> value is set to a JSON array containing the base64 encoded entries of the array returned by the call to the KeyStore API function getCertificateChain.

So pure base64, no \n

**Comment by herrjemand** [comment]
I've added additional checks for that as well

**Comment by herrjemand** [comment]
@jenkay Metadata keyProtection missing does not have neither KEY_PROTECTION_TEE nor KEY_PROTECTION_SOFTWARE flags set.

**Comment by herrjemand** [comment]
@jenkay Waiting for reply from Google on tags related questions.

**Comment by jenkay** [comment]
If we set P-1 to KEY_PROTECTION_TEE instead of KEY_PROTECTION_HARDWARE (to work around the previous), we get this error:

AssertionError: origin MUST be of type INTEGER!: expected ‘SET’ to equal ‘INTEGER’

I looked in the debugger and saw the following. It looks like the AuthorizationList array is being tested for type instead of the 702 element

<img width="849" alt="screen shot 2017-11-20 at 2 49 00 pm" src="https://user-images.githubusercontent.com/5342760/33053605-4b450cf0-ce29-11e7-951c-35fc4a356b75.png">

**Comment by herrjemand** [comment]
@jenkay Sorry for the delay. I was awaiting confirmation from google. This issues is now resolved
