### ISSUE TITLE
Server: Auth-Resp-4 Test fails to generate auth response

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#8]
In Auth-Resp-4, test cases F-2, F-9 and F-10 fail while the test authenticator tries to generate UAF auth response. 

Also, in all of these tests, appID should be set to invalid value after successful registration, and prior to authentication. If not, server will reject the registration.

Auth-Resp-4 Test the FinalChallengeParams dictionary
<img width="628" alt="screen shot 2017-10-20 at 1 17 52 pm" src="https://user-images.githubusercontent.com/5342760/31840195-1b448920-b599-11e7-84e2-ebb046a058b2.png">

**Comment by herrjemand** [comment]
Resolved in v0.9.7
