### ISSUE TITLE
Protocol-Auth-Req-4 F-11, Protocol-Reg-Req-4 F-11

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#90]
Tool Version 0.8.35

Trusted facets “ids” contains empty list.

`{"trustedFacets":[{"version":{"major":1,"minor":0},"ids":[]}]}`

Expected result is UNTRUSTED_FACET_ID(7) client sends PROTOCOL_ERROR
Same test for registration  Protocol-Reg-Req-4 F-11 Expected result is PROTOCOL_ERROR

One of tests has incorrect expected result

**Comment by herrjemand** [comment]
MUST be UNTRUSTED_FACET_ID(7). Found typo in error codes.
Resolved in v0.8.35

**Comment by mlourie** [comment]
How was this resolved in v0.8.35? That was the version of the tool the issue was found.
