### ISSUE TITLE
Error handling for facets file

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#91]
In the specification for the facets file, the specification has no required fields. However, the conformance tool is enforcing that fields are required. We want to make sure we are reading the specification correctly.

The specification says:

"The JSON resource hosted at the AppID URL consists of a dictionary containing a single member, trustedFacets which is an array of TrustedFacets dictionaries."

This does not prohibit the array from being empty. Therefore, PROTOCOL_ERROR should not be returned in that case.

TrustedFacets is defined as follows:

dictionary TrustedFacets {
Version version;
DOMString[] ids;
};

The version and ids are not required.

If we take the specification at face value, the following rules would apply:

If there is no trustedFacets field or it is not an array, return PROTOCOL_ERROR.

Skip TrustedFacet entries when version is missing or not 1.0.

If the version is 1.0 and the ids are missing or empty, return UNTRUSTED_FACETS.

The conformance tool is expecting PROTOCOL_ERROR error in certain cases that the specification doesn't seem to require. I think one of these got fixed, but not all.

**Comment by herrjemand** [comment]
Awaiting TWG discussion

**Comment by herrjemand** [comment]
Per discussion with TWG: 

Syntactically we don't mandate trustedFacets keys to be presented, however procedural side very clearly demands  those fields to be presented. Here is step 16 from appIDandFacets specs:

> After processing the trustedFacets entry of the correct version and removing any invalid entries, if the caller's FacetID matches one listed in ids, the operation is allowed

So PROTOCOL_ERROR would be a valid error code.
