### ISSUE TITLE
UAF 1.0 Auth-Req-4 Timeout

### ISSUE THREAD

**Issue by ockyaditia** [fido-alliance/conformance-tool-issues#95]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Client

## What is the version of the tool are you using?

v0.8.36

## Issue description

Authentication test: Auth-Req-4
Error: Timeout of 2000ms exceeded

Can you increase the timeout for this test?
Thanks.

**Comment by herrjemand** [comment]
I will take a look @ockyaditia

**Comment by herrjemand** [comment]
Increased timeout in the latest version

**Comment by ockyaditia** [comment]
Still produce error: Timeout of 5000ms exceeded on v0.8.41.

And for the Auth-Resp-1, Auth-Resp-2, Auth-Resp-3, Auth-Resp-4, Auth-Resp-5, and Auth-Resp-6 now return error: Timeout of 7500ms exceeded. Whereas in previous version v.08.38 no error for that test cases.

Can you check it?
