### ISSUE TITLE
UAF 1.1 Protocol-Reg-Req-4 not executed test cases

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#98]
There are 10 test cases which are counted in total test number but not executed at all.
Protocol-Reg-Req-4 P-2, P-3, P-5, F-13, F-14, F-15, F-16, F-17, F-18, F-22. There is no any details provided for this tests in final report.

Same kind of empty test cases are exist in  Protocol-Auth-Req-4 and Protocol-Dereg-Req-4 but as far as in version 0.8.36 “before hook” for this test sets are failing so this empty test cases currently not visible for dereg and auth.

**Comment by herrjemand** [comment]
Resolved in v0.8.38
